### PR TITLE
Functionality for logging and plotting KL Divergence

### PR DESCRIPTION
**Pull request by alecokas**
* Introduced two new classes ```GraphLogger``` and ```LogPlotter``` which work together to provide functionality for logging the KL for each factor per epoch and displaying this on a line plot.
* Included an ignore for log files
* Cleaned up some unnecessary imports.

### CODE REVIEW

**Comment by YannDubs** [comment]
Looks good, there will be conflicat with my last PR but it should easily be resolved

**Comment by YannDubs** [comment]
Looks good, there will be conflict with my last PR but it should easily be resolved

you don't use `LogPlotter` yet though, right ?

**Comment by alecokas** [comment]
No, but I did test it to see that it plots the graph as I expected it to

**Comment by YannDubs** [comment]
Nice thx !

**Comment by YannDubs** [comment]
Nice thx!

**Pull request merged**
